# Generated by Django 5.1.2 on 2024-10-18 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trip", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="name",
            field=models.CharField(default="fight", max_length=100),
            preserve_default=False,
        ),
    ]
